name: Deploy WAF

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'agencies/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Export AWS credentials
      run: |
        echo "Exporting AWS credentials..."
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

    - name: Terraform Init
      run: terraform init
      working-directory: agencies/dmv

    - name: Terraform Plan
      run: terraform plan
      working-directory: agencies/dmv

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: agencies/dmv
      