name: Deploy WAF 

on:
  workflow_dispatch:
  push:
    branches:
      - prod
      - stage
      - dev
    paths:
      - 'agencies/dmv/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init - DMV
        run: terraform init
        working-directory: agencies/dmv

      - name: Terraform Plan - DMV
        run: terraform plan
        working-directory: agencies/dmv

      - name: Terraform Apply - DMV
        run: terraform apply -auto-approve
        working-directory: agencies/dmv