name: Deploy WAF

on:
  workflow_dispatch:
  push:
    branches:
      - prod
      - stage
      - dev
    paths:
      - 'agencies/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Detect Changed Agency
        id: detect_agency
        run: |
          git fetch --deepen=100 || true

          echo "Looking for changes in agencies/..."
          CHANGED=$(git diff --name-only HEAD~1 | grep '^agencies/' || true)
          AGENCY=$(echo "$CHANGED" | cut -d'/' -f2 | sort -u | head -n 1)

          if [ -z "$AGENCY" ]; then
            echo "No agency detected. Exiting."
            exit 1
          fi

          echo "AGENCY=$AGENCY" >> $GITHUB_ENV
          echo "Detected agency: $AGENCY"

      - name: Validate Working Directory
        run: |
          echo "Checking if agencies/${{ env.AGENCY }} exists..."
          ls -la agencies/${{ env.AGENCY }}

      - name: Terraform Init
        run: terraform init
        working-directory: agencies/${{ env.AGENCY }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: agencies/${{ env.AGENCY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: agencies/${{ env.AGENCY }}