name: Deploy WAF

on:
  workflow_dispatch:
  push:
    branches:
      - prod
      - stage
      - dev
    paths:
      - 'agencies/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get Changed Agency Folder
        id: get-agency
        run: |
          folder=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'agencies/' | cut -d'/' -f2 | sort -u | head -n 1)
          echo "AGENCY=${folder}" >> $GITHUB_ENV
          echo "Detected agency folder: ${folder}"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: agencies/${{ env.AGENCY }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: agencies/${{ env.AGENCY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: agencies/${{ env.AGENCY }}